#!/usr/bin/env node
/**
 * Owns the body of every catalog resource that is not a decision record.
 *
 *   node scripts/sync-docs.mjs           rewrite the bodies and the summaries that have a source
 *   node scripts/sync-docs.mjs --check   fail if any of them is out of step
 *
 * The catalog documents the platform; it does not narrate it. A page here renders the structure
 * the catalog can verify — the graph, the message table, the schema, the property table — and
 * nothing else. Descriptions come from where the thing is actually defined:
 *
 *   services            the `> [!NOTE]` block in the service's own README
 *   events, commands    the comment above the message in the protobuf contract
 *   queries
 *
 * Resources that are modelling artefacts of this catalog — domains, systems, entities, channels,
 * containers, flows — have no upstream text to draw on. Their frontmatter is the documentation:
 * the steps of a flow, the properties of an entity, the address and delivery guarantee of a
 * channel. Their one-line summary is left as it stands, because EventCatalog requires the field
 * and there is nowhere else to get it from.
 *
 * Frontmatter is hand-maintained catalog structure and is never rewritten here, apart from the
 * summaries listed above.
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const DEFAULT_REF = 'main';

const SKIP = new Set(['node_modules', 'dist', '.git', '.astro', '.eventcatalog-core', 'public', 'adrs']);

const COLLECTIONS = ['services', 'containers', 'entities', 'flows', 'events', 'commands', 'queries', 'channels'];

/**
 * What each kind of page renders. Structure the catalog can show and check — never prose.
 * `<SchemaViewer />` is only added where a schema was actually synced.
 */
const TEMPLATES = {
  services: () => ['<NodeGraph />', '<MessageTable format="all" />'],
  system: () => ['<ContextDiagram />', '<NodeGraph />'],
  domain: () => ['<NodeGraph />'],
  entities: () => ['<EntityPropertiesTable />'],
  channels: () => ['<NodeGraph />'],
  containers: () => ['<NodeGraph />'],
  flows: () => ['<NodeGraph />'],
  events: (fm) => ['<NodeGraph />', ...(fm.schemaPath ? ['<SchemaViewer />'] : [])],
};

TEMPLATES.commands = TEMPLATES.events;
TEMPLATES.queries = TEMPLATES.events;

const MARKER = [
  '{/* The body of this page is generated by scripts/sync-docs.mjs. The catalog renders the',
  '    structure it can verify and takes descriptions from the repositories that define them. */}',
].join('\n');

// ------------------------------------------------------------------------------------------------
// finding the resources
// ------------------------------------------------------------------------------------------------

function findResources(dir, found = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const child = join(dir, entry.name);

    if (entry.isDirectory()) {
      if (!SKIP.has(entry.name)) findResources(child, found);
    } else if (entry.name === 'index.mdx') {
      found.push(child);
    }
  }

  return found;
}

function kindOf(file) {
  const collection = basename(dirname(dirname(file)));

  if (COLLECTIONS.includes(collection)) return collection;
  if (/^domains\/[^/]+\/index\.mdx$/.test(relative(ROOT, file))) return 'domain';

  return 'system';
}

// ------------------------------------------------------------------------------------------------
// where descriptions come from
// ------------------------------------------------------------------------------------------------

async function fetchRaw(url) {
  const res = await fetch(url);

  if (res.status === 404) return null;

  if (!res.ok) throw new Error(`GET ${url} -> ${res.status} ${res.statusText}`);

  return res.text();
}

/** `https://github.com/<owner>/<repo>/tree/<ref>/<path>` -> the raw URL of its README. */
function readmeUrl(repository) {
  const match = repository?.url?.match(/^https:\/\/github\.com\/([^/]+\/[^/]+)\/tree\/([^/]+)\/(.+?)\/?$/);

  if (!match) return null;

  const [, repo, ref, path] = match;

  return `https://raw.githubusercontent.com/${repo}/${ref}/${path}/README.md`;
}

/**
 * The `> [!NOTE]` block a service README opens with. Every service in this platform uses it to say
 * what the service is for, which makes it the one sentence upstream actually maintains.
 */
function readmeNote(markdown) {
  const block = markdown.match(/^>[ \t]*\[!NOTE\][ \t]*\n((?:^>.*\n?)*)/m)?.[1];

  if (!block) return null;

  const text = block
    .split('\n')
    .map((line) => line.replace(/^>[ \t]?/, '').trim())
    .filter(Boolean)
    .join(' ')
    .trim();

  return text && text.length <= 400 ? text : null;
}

/**
 * The comment block above `message <id>` or `rpc <id>` in a protobuf contract. Some schema files
 * hold a single extracted message, others are a whole contract with a dozen; matching on the id
 * keeps a query from being described by whichever message happens to come first.
 */
function protoComment(proto, id) {
  const declaration = new RegExp(`((?:^[ \\t]*//[^\\n]*\\n)+)[ \\t]*(?:message|rpc)[ \\t]+${id}\\b`, 'm');
  const single = /((?:^[ \t]*\/\/[^\n]*\n)+)[ \t]*message[ \t]+\w+/m;
  const messages = (proto.match(/^[ \t]*message[ \t]+\w+/gm) ?? []).length;

  const block = proto.match(declaration)?.[1] ?? (messages === 1 ? proto.match(single)?.[1] : null);

  if (!block) return null;

  const text = block
    .split('\n')
    .map((line) => line.replace(/^[ \t]*\/\/[ \t]?/, '').trim())
    .filter(Boolean)
    // `LinkCreated event - canonical name: link.link.created.v1` names the message, it does not
    // describe it — the canonical name is already the channel address.
    .filter((line) => !/^\w+ (event|command|query) - canonical name:/i.test(line))
    .join(' ')
    .trim();

  return text && text.length <= 400 ? text : null;
}

// ------------------------------------------------------------------------------------------------
// editing
// ------------------------------------------------------------------------------------------------

/**
 * Replaces the `summary` field in place, leaving the rest of the frontmatter byte for byte as it
 * was. Round-tripping through a YAML serialiser would reformat `steps`, `properties` and
 * `dictionary` — large hand-maintained structures this script has no business touching.
 */
function replaceSummary(yaml, value) {
  const rendered = YAML.stringify({ summary: value }, { lineWidth: 0 }).trimEnd();
  const lines = yaml.split('\n');
  const start = lines.findIndex((line) => /^summary:/.test(line));

  if (start === -1) return `${yaml}\n${rendered}`;

  let end = start + 1;

  // A block scalar (`summary: |`) runs on until the next top-level key.
  if (/^summary:[ \t]*[|>]/.test(lines[start])) {
    while (end < lines.length && (lines[end] === '' || /^[ \t]/.test(lines[end]))) end++;
  }

  return [...lines.slice(0, start), rendered, ...lines.slice(end)].join('\n');
}

function renderBody({ kind, fm, repository }) {
  const source = repository?.url ? [`> Source: [${repository.url.replace('https://github.com/', '')}](${repository.url})`, ''] : [];

  return ['', MARKER, '', ...source, ...TEMPLATES[kind](fm), ''].join('\n');
}

// ------------------------------------------------------------------------------------------------
// run
// ------------------------------------------------------------------------------------------------

const results = [];
const readmes = new Map();

for (const file of [...findResources(join(ROOT, 'domains')), ...findResources(join(ROOT, 'systems'))].sort()) {
  const label = relative(ROOT, dirname(file));
  const kind = kindOf(file);
  const text = readFileSync(file, 'utf8');
  const match = text.match(/^---\n([\s\S]*?)\n---\n/);

  if (!match) {
    results.push({ label, status: 'error', detail: 'no frontmatter' });
    continue;
  }

  const yaml = match[1];
  const fm = YAML.parse(yaml);
  let summary = null;
  let detail;

  try {
    if (kind === 'services') {
      const url = readmeUrl(fm.repository);

      if (url) {
        if (!readmes.has(url)) readmes.set(url, await fetchRaw(url));

        const readme = readmes.get(url);

        summary = readme ? readmeNote(readme) : null;
        if (!summary) detail = readme ? 'README has no [!NOTE] block' : 'no README upstream';
      }
    } else if (['events', 'commands', 'queries'].includes(kind) && fm.schemaPath) {
      const schema = join(dirname(file), fm.schemaPath);

      if (existsSync(schema) && fm.schemaPath.endsWith('.proto')) {
        summary = protoComment(readFileSync(schema, 'utf8'), fm.id);
        if (!summary) detail = 'no comment on the message in the contract';
      }
    }
  } catch (error) {
    results.push({ label, status: 'error', detail: error.message });
    continue;
  }

  const updatedYaml = summary ? replaceSummary(yaml, summary) : yaml;
  const content = `---\n${updatedYaml}\n---\n${renderBody({ kind, fm, repository: fm.repository })}`;

  if (content === text) {
    results.push({ label, status: 'ok' });
    continue;
  }

  if (CHECK) {
    results.push({ label, status: 'outdated', detail });
    continue;
  }

  writeFileSync(file, content);
  results.push({ label, status: summary ? 'described' : 'stripped', detail });
}

// ------------------------------------------------------------------------------------------------
// report
// ------------------------------------------------------------------------------------------------

const LABELS = {
  ok: '  ok        ',
  described: '  described ',
  stripped: '  stripped  ',
  outdated: '  OUTDATED  ',
  error: '  ERROR     ',
};

for (const { label, status, detail } of results) {
  console.log(`${LABELS[status]} ${label}${detail ? ` — ${detail}` : ''}`);
}

console.log('');

const problems = results.filter((r) => ['outdated', 'error'].includes(r.status));
const changed = results.filter((r) => ['described', 'stripped'].includes(r.status));

if (problems.length > 0) {
  console.error(
    CHECK
      ? `${problems.length} of ${results.length} page(s) are out of step.\n` +
          'Run `npm run sync:docs`, review the diff, and commit it.'
      : `${problems.length} page(s) could not be processed.`,
  );
  process.exit(1);
}

console.log(
  CHECK
    ? `All ${results.length} pages match their sources.`
    : changed.length > 0
      ? `${changed.length} page(s) written.`
      : `All ${results.length} pages already up to date.`,
);
